### ISSUE TITLE
Lifetime issues

### ISSUE THREAD

**Issue by user706** [qduyang/chrono#1]
Hi,

are you aware that your timer has lifetime issues?

If the timer-callback is running, and the timer destructs while the timer-callback is running, you have these lifetime issues, which I personally see as a bug.

I see them as a bug, because the timer can fire at any time (set e.g. through a variable), and the destruction of the timer should be safe, in all situations, even if it occurs while the callback is running. This is my opinion.

To see what I'm talking about, try this repo https://github.com/user706/chrono/tree/mine in branch called `mine`, where I've added a new test to `test/test_timer.cpp` (see [here](https://github.com/user706/chrono/commit/d4589ae0f9b691701ab8c7b74c138535b0719002))

**Comment by user706** [comment]
> To see what I'm talking about, try this repo https://github.com/user706/chrono/tree/mine in branch called `mine`, where I've added a new test to `test/test_timer.cpp` (see [here](https://github.com/user706/chrono/commit/d4589ae0f9b691701ab8c7b74c138535b0719002))

Note that the order of destruction in my example is:
`timer_` destructs first, then `spi_` destructs, then `i_` destructs (see [here](https://github.com/user706/chrono/commit/d4589ae0f9b691701ab8c7b74c138535b0719002#diff-4a226ce65367d40c4228cca424084393R49) and the 2 lines above that).

**Comment by qduyang** [comment]
Hi, yes it is do a lifetime issue, but it is a lifetime issue of the variables which the callback referenced.
Once the timer-callback is running, we are no longer able to stop/interrupt it (here the callback is sleeping for 50 ms). As the timer callback has reference access to you class member spi_ & i_, once they were destructed, the callback will run into a segment fault.

To fix it, please use value-capture instead of reference-capture for the timer lambda callback. e.g.
```c++
timer_.Start([i_ = i_, spi_ = spi_]() {
      std::this_thread::sleep_for(std::chrono::milliseconds(50));
      std::cout << "i_        => " << i_ << std::endl;
      std::cout << "spi_->i() => " << spi_->i() << std::endl;
    });
```
